apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-fedora-golden-image
  namespace: vm-infra-pipelines
spec:
  params:
    - name: image_name
      default: "quay.io/knav3/fedora-golden:latest"
  workspaces:
    - name: shared-data
  steps:
    - name: virt-builder
      image: quay.io/kubevirt/virt-utils@sha256:07455e905333f207038167f4019448d1c95107e155460596e16f809930f3c552
      securityContext:
        privileged: true
      script: |
        #!/usr/bin/env bash
        set -e
        
        # Move to the workspace
        cd $(workspaces.shared-data.path)

        # Build the image
        virt-builder fedora-39 \
          --output fedora.qcow2 \
          --install httpd \
          --run-command "systemctl enable httpd" \
          --run-command "useradd -m dirk" \
          --password dirk:password:redhatocp \
          --selinux-relabel

        # Buildah push
        echo "FROM scratch" > Dockerfile
        echo "ADD fedora.qcow2 /disk/" >> Dockerfile
        buildah --storage-driver=vfs bud -t $(params.image_name) .
        buildah --storage-driver=vfs push $(params.image_name)
