apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-webserver
  namespace: fedora-web-prod
  labels:
    app: web
spec:
  running: true
  template:
    metadata:
      labels:
        app: web
    spec:
      domain:
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 8Gi 
            cpu: 4 
        machine:
          type: pc-q35-rhel9.4.0
        firmware:
          bootloader:
            efi: {}
        features:
          smm:
            enabled: true
        devices:
          disks:
            - disk: {bus: virtio}
              name: rootdisk
            - disk: {bus: virtio}
              name: cloudinitdisk # Added for cloud-init
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/knav3/fedora-golden:cloud-v1 # Your new image
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: dirk
              password: password:redhatocp
              chpasswd: { expire: False }
              sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
              packages:
                - httpd
              write_files:
                - content: |
                    <html>
                    <body>
                      <h1>You are now viewing Dirk's Golden Image</h1>
                      <p>Hosted on <strong>OpenShift Virtualization</strong> via Cloud-Init</p>
                    </body>
                    </html>
                  path: /var/www/html/index.html
              runcmd:
                - [ systemctl, enable, --now, httpd ]
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fedora-web-root
spec:
  source:
    registry:
      url: "docker://quay.io/knav3/fedora-golden:latest"
  storage:
    resources:
      requests:
        storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-web-svc
  namespace: fedora-web-prod
  labels:
    app: web
spec:
  selector:
    app: web 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fedora-web-route
  namespace: fedora-web-prod
  labels:
    app: web
spec:
  to:
    kind: Service
    name: fedora-web-svc
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
