apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-webserver
  namespace: fedora-web-prod
  labels:
    app: web
spec:
  running: true
  template:
    metadata:
      labels:
        app: web
    spec:
      domain:
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi 
            cpu: 2 
        machine:
          type: pc-q35-rhel9.4.0
        firmware:
          bootloader:
            efi: {}
        features:
          smm:
            enabled: true
        devices:
          disks:
            - disk: {bus: virtio}
              name: rootdisk
            - disk: {bus: virtio}
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      volumes:
        # --- Changed from containerDisk to dataVolume ---
        - name: rootdisk
          dataVolume:
            name: fedora-web-root-dv
        # ------------------------------------------------
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: dirk
              password: password:redhatocp
              chpasswd: { expire: False }
              sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
              packages:
                - httpd
              write_files:
                - content: |
                    <html>
                    <body>
                      <h1>You are now viewing Dirk's Golden Image</h1>
                      <p>Hosted on <strong>OpenShift Virtualization</strong> via Cloud-Init</p>
                    </body>
                    </html>
                  path: /var/www/html/index.html
              runcmd:
                - [ systemctl, enable, --now, httpd ]

  # --- This is the new 20GB Persistent Disk Template ---
  dataVolumeTemplates:
    - metadata:
        name: fedora-web-root-dv
      spec:
        source:
          registry:
            url: "docker://quay.io/knav3/fedora-golden:cloud-v1"
        storage:
          resources:
            requests:
              storage: 20Gi
          # Using your Ceph RBD 'immediate' storage class
          storageClassName: ocs-external-storagecluster-ceph-rbd-immediate
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-web-svc
  namespace: fedora-web-prod
  labels:
    app: web
spec:
  selector:
    app: web 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fedora-web-route
  namespace: fedora-web-prod
  labels:
    app: web
spec:
  to:
    kind: Service
    name: fedora-web-svc
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
